/**
 * @description
 * This file was generated from the execution result of the `npm run zonename` command.
 */

export default {
  'Acre Standard Time': 'ACT',
  'Acre Summer Time': 'ACST',
  'Afghanistan Time': 'AFT',
  'Alaska Daylight Time': 'AKDT',
  'Alaska Standard Time': 'AKST',
  'Almaty Standard Time': 'ALMT',
  'Almaty Summer Time': 'ALMST',
  'Amazon Standard Time': 'AMT',
  'Amazon Summer Time': 'AMST',
  'American Samoa Standard Time': 'SST',
  'Anadyr Standard Time': 'ANAT',
  'Anadyr Summer Time': 'ANAST',
  'Aqtau Standard Time': 'AQTT',
  'Aqtau Summer Time': 'AQTST',
  'Aqtobe Standard Time': 'AQTT',
  'Aqtobe Summer Time': 'AQTST',
  'Arabian Daylight Time': 'ADT',
  'Arabian Standard Time': 'AST',
  'Argentina Standard Time': 'ART',
  'Argentina Summer Time': 'ARST',
  'Armenia Standard Time': 'AMT',
  'Armenia Summer Time': 'AMST',
  'Atlantic Daylight Time': 'ADT',
  'Atlantic Standard Time': 'AST',
  'Australian Central Daylight Time': 'ACDT',
  'Australian Central Standard Time': 'ACST',
  'Australian Central Western Daylight Time': 'ACWDT',
  'Australian Central Western Standard Time': 'ACWST',
  'Australian Eastern Daylight Time': 'AEDT',
  'Australian Eastern Standard Time': 'AEST',
  'Australian Western Daylight Time': 'AWDT',
  'Australian Western Standard Time': 'AWST',
  'Azerbaijan Standard Time': 'AZT',
  'Azerbaijan Summer Time': 'AZST',
  'Azores Standard Time': 'AZOT',
  'Azores Summer Time': 'AZOST',
  'Bangladesh Standard Time': 'BST',
  'Bangladesh Summer Time': 'BDST',
  'Bhutan Time': 'BTT',
  'Bolivia Time': 'BOT',
  'Brasilia Standard Time': 'BRT',
  'Brasilia Summer Time': 'BRST',
  'British Summer Time': 'BST',
  'Brunei Time': 'BNT',
  'Cape Verde Standard Time': 'CVT',
  'Casey Time': 'CAST',
  'Central Africa Time': 'CAT',
  'Central Daylight Time': 'CDT',
  'Central European Standard Time': 'CET',
  'Central European Summer Time': 'CEST',
  'Central Indonesia Time': 'WITA',
  'Central Standard Time': 'CST',
  'Chamorro Standard Time': 'ChST',
  'Chatham Daylight Time': 'CHADT',
  'Chatham Standard Time': 'CHAST',
  'Chile Standard Time': 'CLT',
  'Chile Summer Time': 'CLST',
  'China Daylight Time': 'CDT',
  'China Standard Time': 'CST',
  'Christmas Island Time': 'CXT',
  'Chuuk Time': 'CHUT',
  'Cocos Islands Time': 'CCT',
  'Colombia Standard Time': 'COT',
  'Colombia Summer Time': 'COST',
  'Cook Islands Standard Time': 'CKT',
  'Cook Islands Summer Time': 'CKST',
  'Coordinated Universal Time': 'UTC',
  'Cuba Daylight Time': 'CDT',
  'Cuba Standard Time': 'CST',
  'Davis Time': 'DAVT',
  'Dumont d’Urville Time': 'DDUT',
  'East Africa Time': 'EAT',
  'East Greenland Standard Time': 'EGT',
  'East Greenland Summer Time': 'EGST',
  'East Kazakhstan Time': 'ALMT',
  'Easter Island Standard Time': 'EAST',
  'Easter Island Summer Time': 'EASST',
  'Eastern Daylight Time': 'EDT',
  'Eastern European Standard Time': 'EET',
  'Eastern European Summer Time': 'EEST',
  'Eastern Indonesia Time': 'WIT',
  'Eastern Standard Time': 'EST',
  'Ecuador Time': 'ECT',
  'Falkland Islands Standard Time': 'FKST',
  'Falkland Islands Summer Time': 'FKST',
  'Fernando de Noronha Standard Time': 'FNT',
  'Fernando de Noronha Summer Time': 'FNST',
  'Fiji Standard Time': 'FJT',
  'Fiji Summer Time': 'FJST',
  'French Guiana Time': 'GFT',
  'French Southern & Antarctic Time': 'TFT',
  'Further-eastern European Time': 'FET',
  'Galapagos Time': 'GALT',
  'Gambier Time': 'GAMT',
  'Georgia Standard Time': 'GET',
  'Georgia Summer Time': 'GEST',
  'Gilbert Islands Time': 'GILT',
  'Greenland Standard Time': 'GT',
  'Greenland Summer Time': 'GST',
  'Greenwich Mean Time': 'GMT',
  'Guam Standard Time': 'ChST',
  'Gulf Standard Time': 'GST',
  'Guyana Time': 'GYT',
  'Hawaii-Aleutian Daylight Time': 'HADT',
  'Hawaii-Aleutian Standard Time': 'HAST',
  'Hong Kong Standard Time': 'HKT',
  'Hong Kong Summer Time': 'HKST',
  'Hovd Standard Time': 'HOVT',
  'Hovd Summer Time': 'HOVST',
  'India Standard Time': 'IST',
  'Indian Ocean Time': 'IOT',
  'Indochina Time': 'ICT',
  'Iran Daylight Time': 'IRDT',
  'Iran Standard Time': 'IRST',
  'Irish Standard Time': 'IST',
  'Irkutsk Standard Time': 'IRKT',
  'Irkutsk Summer Time': 'IRKST',
  'Israel Daylight Time': 'IDT',
  'Israel Standard Time': 'IST',
  'Japan Standard Time': 'JST',
  'Kamchatka Standard Time': 'PETT',
  'Kamchatka Summer Time': 'PETST',
  'Kazakhstan Time': 'KZT',
  'Korean Daylight Time': 'KDT',
  'Korean Standard Time': 'KST',
  'Kosrae Time': 'KOST',
  'Krasnoyarsk Standard Time': 'KRAT',
  'Krasnoyarsk Summer Time': 'KRAST',
  'Kyrgyzstan Time': 'KGT',
  'Lanka Time': 'LKT',
  'Line Islands Time': 'LINT',
  'Lord Howe Daylight Time': 'LHDT',
  'Lord Howe Standard Time': 'LHST',
  'Macao Standard Time': 'CST',
  'Macao Summer Time': 'CST',
  'Magadan Standard Time': 'MAGT',
  'Magadan Summer Time': 'MAGST',
  'Malaysia Time': 'MYT',
  'Maldives Time': 'MVT',
  'Marquesas Time': 'MART',
  'Marshall Islands Time': 'MHT',
  'Mauritius Standard Time': 'MUT',
  'Mauritius Summer Time': 'MUST',
  'Mawson Time': 'MAWT',
  'Mexican Pacific Daylight Time': 'PDT',
  'Mexican Pacific Standard Time': 'PST',
  'Moscow Standard Time': 'MSK',
  'Moscow Summer Time': 'MSD',
  'Mountain Daylight Time': 'MDT',
  'Mountain Standard Time': 'MST',
  'Myanmar Time': 'MMT',
  'Nauru Time': 'NRT',
  'Nepal Time': 'NPT',
  'New Caledonia Standard Time': 'NCT',
  'New Caledonia Summer Time': 'NCST',
  'New Zealand Daylight Time': 'NZDT',
  'New Zealand Standard Time': 'NZST',
  'Newfoundland Daylight Time': 'NDT',
  'Newfoundland Standard Time': 'NST',
  'Niue Time': 'NUT',
  'Norfolk Island Daylight Time': 'NFDT',
  'Norfolk Island Standard Time': 'NFT',
  'North Korea Time': 'KST',
  'Northern Mariana Islands Time': 'CHST',
  'Novosibirsk Standard Time': 'NOVT',
  'Novosibirsk Summer Time': 'NOVST',
  'Omsk Standard Time': 'OMST',
  'Omsk Summer Time': 'OMSST',
  'Pacific Daylight Time': 'PDT',
  'Pacific Standard Time': 'PST',
  'Pakistan Standard Time': 'PKT',
  'Pakistan Summer Time': 'PKST',
  'Palau Time': 'PWT',
  'Papua New Guinea Time': 'PGT',
  'Paraguay Standard Time': 'PYT',
  'Paraguay Summer Time': 'PYST',
  'Peru Standard Time': 'PET',
  'Peru Summer Time': 'PEST',
  'Philippine Standard Time': 'PST',
  'Philippine Summer Time': 'PHST',
  'Phoenix Islands Time': 'PHOT',
  'Pitcairn Time': 'PIT',
  'Pohnpei Time': 'PONT',
  'Qyzylorda Standard Time': 'QYZT',
  'Qyzylorda Summer Time': 'QYZST',
  'Rothera Time': 'ROTT',
  'Réunion Time': 'RET',
  'Sakhalin Standard Time': 'SAKT',
  'Sakhalin Summer Time': 'SAKST',
  'Samara Standard Time': 'SAMT',
  'Samara Summer Time': 'SAMST',
  'Samoa Daylight Time': 'SDT',
  'Samoa Standard Time': 'SST',
  'Seychelles Time': 'SCT',
  'Singapore Standard Time': 'SGT',
  'Solomon Islands Time': 'SBT',
  'South Africa Standard Time': 'SAST',
  'South Georgia Time': 'GST',
  'St. Pierre & Miquelon Daylight Time': 'PMDT',
  'St. Pierre & Miquelon Standard Time': 'PMST',
  'Suriname Time': 'SRT',
  'Syowa Time': 'SYOT',
  'Tahiti Time': 'TAHT',
  'Taiwan Daylight Time': 'CDT',
  'Taiwan Standard Time': 'CST',
  'Tajikistan Time': 'TJT',
  'Timor-Leste Time': 'TLT',
  'Tokelau Time': 'TKT',
  'Tonga Standard Time': 'TOT',
  'Tonga Summer Time': 'TOST',
  'Turkmenistan Standard Time': 'TMT',
  'Tuvalu Time': 'TVT',
  'Ulaanbaatar Standard Time': 'ULAT',
  'Ulaanbaatar Summer Time': 'ULAST',
  'Uruguay Standard Time': 'UYT',
  'Uruguay Summer Time': 'UYST',
  'Uzbekistan Standard Time': 'UZT',
  'Uzbekistan Summer Time': 'UZST',
  'Vanuatu Standard Time': 'VUT',
  'Vanuatu Summer Time': 'VUST',
  'Venezuela Time': 'VET',
  'Vladivostok Standard Time': 'VLAT',
  'Vladivostok Summer Time': 'VLAST',
  'Volgograd Standard Time': 'VOLT',
  'Volgograd Summer Time': 'VOLST',
  'Vostok Time': 'VOST',
  'Wake Island Time': 'WAKT',
  'Wallis & Futuna Time': 'WFT',
  'West Africa Standard Time': 'WAT',
  'West Africa Summer Time': 'WAST',
  'West Greenland Standard Time': 'WGT',
  'West Greenland Summer Time': 'WGST',
  'West Kazakhstan Time': 'AQTT',
  'Western Argentina Standard Time': 'ART',
  'Western Argentina Summer Time': 'ARST',
  'Western European Standard Time': 'WET',
  'Western European Summer Time': 'WEST',
  'Western Indonesia Time': 'WIB',
  'Yakutsk Standard Time': 'YAKT',
  'Yakutsk Summer Time': 'YAKST',
  'Yekaterinburg Standard Time': 'YEKT',
  'Yekaterinburg Summer Time': 'YEKST',
  'Yukon Time': 'YT'
};
