name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run linter
      run: npm run lint

    - name: Run tests
      run: npm test

  coverage:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests with coverage
      run: npm run test:coverage

    - name: Read coverage summary
      id: coverage
      run: |
        echo "summary=$(cat coverage/coverage-summary.json)" >> $GITHUB_OUTPUT

    - name: Generate coverage badge
      uses: emibcn/badge-action@v2.0.3
      with:
        label: 'coverage'
        status: ${{ fromJson(steps.coverage.outputs.summary).total.lines.pct }}%
        color: ${{ fromJson(steps.coverage.outputs.summary).total.lines.pct > 80 && 'brightgreen' || fromJson(steps.coverage.outputs.summary).total.lines.pct > 60 && 'yellow' || 'red' }}
        path: badges/coverage.svg
        style: flat

    - name: Commit coverage badge
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        mkdir -p badges
        git add badges/coverage.svg
        git diff --staged --quiet || git commit -m "Update coverage badge"
        git push

    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage/